### ISSUE TITLE
Ignore commits per Ignored Folder/File

### ISSUE THREAD

**Issue by Akhliskun** [mozilla-releng/firefox-infra-changelog#114]
Please create a separate file, that uses the existing functionality of the tool, and choose a repository (one that is "busy") and make a **proof of concept that will ignore commits if**:
- Version is not released (not in production)
- Commits happened in a folder that we ignore
- Commits happened on a file that we ignore.

You can choose any repo, folder and files. As a starting point, look for a repository (such as build-puppet) and check their existing commits, see which files are being edited and take them and mark them as "ignored". Doesn't matter which files or folders you ignore, this is a proff of concept, we wan't the functionality not the "production ready code".

At the end, please detail exactly how the logic runs and why.

**Comment by mutterroland** [comment]
I'll try my best in explaining what I've done so far so here we go.

First of all , I've inspected the git.get_repo.get_commits object to see if there is any information related to files. Found the following: 

- a list called "files" that contains information about files that were modified in that commit
- it can be iterated with a for loop eg: **for entry in commit.files** inside **for commit in git.get_repo(repository_path).get_commits(since=previous_release)**
- for the next step we'll take as an example a commit that has 3 different files changed. Imagine we have to ignore modules folder and moco-config.pp file in build-puppet. 

I've tried hardcoding ignoring modules folder by **if "modules" not in entry.filename: Do logic.**
Seems like everything worked here but the problems started to appear when trying to check for a file and a folder at the same time : **if "modules" or "moco-config.pp" not in entry.filename: do logic**

From my point of view we have to do the following:

- As "folders/files-to-ignore" is a list , we have to get the folders/files to ignore from there (not a big deal)
- Getting jsons containing commits in append mode ( This stands only if the checks will be done 1 by 1 and not all at the same time)
- Find some kind of logic to check commits gradually / all of the same time if possible

**Comment by zsoltfay** [comment]
I've changed up the logic in filter_git_commit_data: 

- With the local testing i did so far the script is working even if we have multiple files that we need to ignore
- Also added "files-we-care-about" to the config and it seems to work as well

If a commit only changes one file it's easy to decide whether we care about it or not. Tried to implement checks for any possible scenario that we can come across when a commit changes multiple files/folders:

1. If any of the files changed is one that we care about = we want to save the commit 
2. For repos that don't have specific files we need to care for (usually means we care about all or almost all files). In this case we have 2 possibilities:
                                         - only files we can ignore changed = we can ignore the commit
                                         - some file we can ignore but others we care about = we save the commit
3. If the files that changed in a commit aren't defined in neither files-we-care-about or files-we-ignore it usually means we care about everything in this specific repo = we want the commit

The code can be broken down into several smaller functions, which is probably what we should do. 
As we are going to have repositories configured differently (some will have files we need to ignore, while others will have only certain files we care about). And such we can call upon the function that we need.

As it stand at the moment the proof of concept is working. Now it's time to polish it. Feel free to comment in case I forgot to check for a certain situation that might occur or if i missed something in the logic.

**Comment by raduiman** [comment]
- git returns the status of each file (e.g modified, removed, added) I have managed to save this information in the JSON file as following (build-puppet repo):
     "files_changed": {
        "modules/generic_worker/manifests/init.pp": "modified",
        "modules/generic_worker/templates/run-generic-worker.sh.erb": "modified",
        "modules/grub/templates/defaults.erb": "modified"
     }
 - in this case my thoughts are:
   1.  we can quit the lists of the files and folders that we should ignore ( "folders-to-ignore", "files-to-ignore")
   2. compare the  "files_changed" list with the list of the files we care about ("files_to_care_for") and save the commit in case of match
   3. in case of a new file (status = added) -> save the commit

What do you think about it?

**Comment by bccrisan** [comment]
Having the lists of files and folders that we should ignore it is not a bad idea, a bad idea would be just having that.
We should also have files and folders to care about, besides the files and folders to ignore.

The logic (as discussed in the meeting with aki) should contain a priority checker, that should check for a specific type (to care for / to ignore). 
That would depend on every repo, what files and folders we want to care about or to ignore.

We can implement something like, checking the number of elements in each list:

`if len(ignore_list) >= len(care_list):`
`    # filter for the list which contains files and folders we care about`
`    # the idea is to have as fewer elements to filter for as possible.`
`else:`
`    # filter for the ignore list, since the ignore list would have fewer elements`

**Comment by zsoltfay** [comment]
This logic has been implemented for both git and hg and is working as expected.
