### ISSUE TITLE
Define a json file that stores all of the repositories

### ISSUE THREAD

**Issue by bccrisan** [mozilla-releng/firefox-infra-changelog#29]
Define a json file that stores all of the git and hg repositories in a single place

My solution to this problem would be a json file that would look something like this:
```json
{
  "HG": {
    "Repo_HG1": "link1",
    "Repo_HG2": "link2",
    "Repo_HG3": "link3"
  },
  "Git": {
    "Repo_GIT1": "link1",
    "Repo_GIT2": "link2",
    "Repo_GIT3": "link3"
  }
}
```
Another option would be using a convertor, but most of them needs to be installed and kept up to date.

Also a big advantage would be the simplicity that would give in case we want to store another data in those repositories, e.g specific files to check.
```json
{
  "HG": {
    "Repo_HG1": {
      "link": "https://example.com",
      "important_file": "https://example.com/important",
      "file_to_ignore": "https://example.com/ignore"
    },
    "Repo_HG2": "link2",
    "Repo_HG3": "link3"
  },
  "Git": {
    "Repo_GIT1": "link1",
    "Repo_GIT2": "link2",
    "Repo_GIT3": "link3"
  }
}
```

**Comment by Akhliskun** [comment]
**2 notes**:
1) Please use styles when posting code. You can use the triple ` (Tilda btn without shift) and language name.
This way we will keep code easy to read. I have edited the proposal for you to include the language syntax.

2) We will need extra keys inside the dictionary, that will track repository config. this will aid us on how to find if code inside a repository actually landed in production. 
This we can talk about with @lundjordan during a 1x1.

**Comment by Akhliskun** [comment]
I have came back with an example, we could use something like this:
```json
{
  "Github": {
    "ship-it": {
      "name": "Ship-It",
      "url": "https://github.com/mozilla-releng/ship-it",
      "team": "mozilla-releng",
      "top-contributors": ["sylvestre", "mozbhearsum"],
      "configuration": {
        "type": "Unknown",
        "folders-to-ignore": ["list", "of", "folders"],
        "files-to-ignore": ["list", "of", "files"],
        "release-path": "Unknown"
      }
    }
  }
}
```

## How to use it
First few obvious areas/features are that we have nested keys, I will cover each of them and how we could use them and even expand in the future:

- "Github" - VCS, could be Github or HG
- "ship-it" - Repository name, all lowercase and "-" between words.
- "name", "url" - Self explanatory.
- "team" - Used when generating the link. Or for easy tracking on which team hosts the repository.
- "top-contributors": Used by us, or anyone who needs to know who is mozilla is actively maintaint a repository. **If we have more than 1 contributor, this value of this key should always be a list**.
- "configuration" - Will keep more sub-keys (nested keys) that the CLI will work with, so that we know what we need to ignore.
- "type" - Is it puppet, occ, scriptworker controlled?
- "folders/files-to-ignore" - self-explanatory
- "release-path" - This will be very important, as the CLI will use this path to find out if a change/pr/commit has landed to production yet. This could be a link to a release page for example (or versioning page, etc).


@lundjordan Have I missed something here?

**Comment by lundjordan** [comment]
The "type" field will need meta-data depending on what that value is. So if it's puppet, you need to specify where to find in puppet what version/revision is currently "live" in prod.
