### ISSUE TITLE
Save only the version-bumping commit in script repositories

### ISSUE THREAD

**Issue by zsoltfay** [mozilla-releng/firefox-infra-changelog#319]
At the moment, when it comes to *script repos, we are getting every new commit up until the one that changed the version. 
Since the commit that changes the version is what could affect infra, it would be more efficient if we would save only the commit that bumps the version.

**Comment by Akhliskun** [comment]
Issue is missing:

- Pointers inside our tool that shows the code that currently deals with this logic.
- Example of commit that needs to be saved.
- Possible Implementations.

I have done the bug/feature templates to be used, not deleted.

**Comment by raduiman** [comment]
WIP - branch issue-319: 
- changed the type of the script repositories with type=script
- modified 'filter_git_scriptworkers' function to track only the script repositories (repos with type=script)
- the function checks each commit since the last check until the last version
TODO:
- add an if statement, to check if the commit message contains the version-bump and save it
```Python:
if commit contains the tag:
       each_commit2.update({int(commit_number): commit_details})
       new_scriptworker_dict.update(each_commit2)
else:
      pass
```

**Comment by zsoltfay** [comment]
This has been done in PR #360
