### ISSUE TITLE
Trim commit description.

### ISSUE THREAD

**Issue by Akhliskun** [mozilla-releng/firefox-infra-changelog#389]
This is a sub-issue of #382 

**This should only affect the .md files for the repository! Not changelog.md/json or all the {repo-name}.json**

- [x] Check if description length is longer than 400 characters
- [x] Insert "Continue Reading" link for trimmed descriptions
- [x] Regenerate all repo-name.md files to follow this new requirement

**Comment by bccrisan** [comment]
The regeneration of the git_files/*.md and hg_files/*.md will be done at the next run of the script.
I will not push those changes manually since it may brake things and have merge conflicts.

**Comment by bccrisan** [comment]
All of the checks and continue reading + link is done in function `trim_commit_description()`:
```Python
def trim_commit_description(message,
                            commit_link,
                            length=COMMIT_DESCRIPTION_LENGTH):
    """
    Implemented in: issue-389
    This function checks if the length of the message (that is applied to
    commit description) is larger then a defined length.
    The length of the commit it's stored in configuration.py and it's value can
    be modified in two ways:
        1. In configuration.py modify the COMMIT_DESCRIPTION_LENGTH
        2. Overwrite it by providing the 3rd argument when the function is
        called.
    In the case of a message that it's larger then the defined length, the
    supplied commit_link will be used with a "continue reading" message that
    should redirect to the commit link (git/mercurial link)

    :param commit_link: commit link that will be used for generating the
    "continue reading..." link message
    :param message: commit description that is checked to see if it has the
    proper length
    :param length: optional, type=int and predefined in configuration.py with

    :return:
    """
    link_message = ""

    if len(message) > length:
        link_message = "... [continue reading...](" + commit_link + ")"

    result_message = message[0:length] + link_message
    return result_message
```

Code explanation and important bits from the above code:
 - 1. Checks the length of the provided message to see if it's greater than a defined number (in configuration.py) and if that's true, construct the message `link_message ` that it's used to create the continue reading message.
```Python
 if len(message) > length:
        link_message = "... [continue reading...](" + commit_link + ")"
```
 - 2. This constructs the `result_message` by concatenating the first 400 (in our case) characters from the provided message and the link message that has been previously generated.
```Python
result_message = message[0:length] + link_message
```

I have choose to do it this way because the code doesn't have to check every time if the provided message it's larger than 400 chars, 

A simplified version of the above code will be pushed:
```Python
    if len(message) > length:
        return message[0:length] + ".. [continue reading](" + commit_link + ")"
    return message

```
